# Generated by Django 4.1.7 on 2023-06-06 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appgalter', '0002_rename_proveedor_material_proveedor_mate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cant_mate',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Appgalter.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_encargo',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='tiempo_pedido',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario_pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Appgalter.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='long_prod',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='prec_prod',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='tiempo_prod',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_cliente',
            field=models.TextField(max_length=15),
        ),
        migrations.AlterField(
            model_name='material',
            name='proveedor_mate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appgalter.proveedor'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='producto_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appgalter.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='material_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appgalter.material'),
        ),
    ]
