# Generated by Django 4.1.7 on 2023-06-20 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appgalter', '0003_material_cant_mate_pedido_cliente_pedido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='pass_ususario',
            new_name='pass_usuario',
        ),
    ]
