# Generated by Django 4.1.7 on 2023-06-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appgalter', '0004_rename_pass_ususario_usuario_pass_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='telefono_proveedor',
            field=models.TextField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
