# Generated by Django 4.1.7 on 2023-06-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appgalter', '0005_proveedor_telefono_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telefono_proveedor',
            field=models.TextField(max_length=15),
        ),
    ]
