# Generated by Django 4.1.7 on 2023-06-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appgalter', '0006_alter_proveedor_telefono_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='proveedor_mate',
            field=models.TextField(max_length=50),
        ),
    ]
