# Generated by Django 4.1.7 on 2023-06-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appgalter', '0007_alter_material_proveedor_mate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='material_prod',
            field=models.TextField(max_length=50),
        ),
    ]
