# Generated by Django 4.1.7 on 2023-06-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appgalter', '0009_alter_material_proveedor_mate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='proveedor_mate',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='material_prod',
            field=models.TextField(max_length=50),
        ),
    ]
