# Generated by Django 4.1.7 on 2023-07-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appgalter', '0010_alter_material_proveedor_mate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente_pedido',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='producto_pedido',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario_pedido',
            field=models.TextField(max_length=50),
        ),
    ]
