# Generated by Django 4.1.7 on 2023-08-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appgalter', '0012_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='pass_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido_usuario',
            field=models.TextField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
